# This is a basic workflow to help you get started with Actions

name: myext

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  windows:
    defaults:
      run:
        shell: cmd
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP with PECL extension
        uses: zephir-lang/setup-php-sdk@v1.0
        with:
          php_version: '7.4'
          ts: 'nts'
          msvc: 'vs16'
          arch: 'x64'
          install_dir: 'C:\tools'
          cache_dir: 'C:\Downloads'
      - name: phpize
        run: phpize
      - name: configure
        run: configure --enable-myext --with-prefix=${{steps.setup-php.outputs.prefix}} --with-extra-includes=.\libs --with-extra-libs=.\libs
      - name: make
        run: nmake
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: D:\a\php_myext\php_myext\php-bin
        
